# -*- coding: utf-8 -*-
from config.settings import settings

DATA_SYNC_TASKS = {
    "trade_cal": {
        "name": "交易日历",
        "api": "trade_cal",
        "mode": "once",
        "schedule": "0 6 * * *",
        "priority": 0,
        "verify_sample_size": 0,
        "params": {"exchange": ""},
        "fields": {
            "exchange": ("str", "交易所", True),
            "cal_date": ("date", "日历日期", True),
            "is_open": ("int", "是否交易", False),
            "pretrade_date": ("date", "上一交易日", False),
        },
        "is_timescale": False,
    },
    "stock_basic": {
        "name": "股票基本信息",
        "api": "stock_basic",
        "mode": "once",
        "schedule": "0 7 * * *",
        "priority": 1,
        "verify_sample_size": 0,
        "params": {"exchange": "", "list_status": "L"},
        "fields": {
            "ts_code": ("str", "TS代码", True),
            "symbol": ("str", "代码", False),
            "name": ("str", "名称", False),
            "area": ("str", "地域", False),
            "industry": ("str", "行业", False),
            "fullname": ("str", "全称", False),
            "market": ("str", "市场", False),
            "exchange": ("str", "交易所", False),
            "curr_type": ("str", "货币", False),
            "list_status": ("str", "状态", False),
            "list_date": ("date", "上市日", False),
            "delist_date": ("date", "退市日", False),
            "is_hs": ("str", "沪深港通", False),
        },
        "is_timescale": False,
    },
    "daily": {
        "name": "日线行情",
        "api": "daily",
        "mode": "incremental",
        "date_field": "trade_date",
        "schedule": "0 18 * * 1-5",
        "priority": 2,
        "oldest_date": "19910101",
        "api_date_type": "single",
        "verify_sample_size": 5,
        "fields": {
            "ts_code": ("str", "代码", True),
            "trade_date": ("date", "日期", True),
            "open": ("float", "开盘", False),
            "high": ("float", "最高", False),
            "low": ("float", "最低", False),
            "close": ("float", "收盘", False),
            "pre_close": ("float", "昨收", False),
            "change": ("float", "涨跌额", False),
            "pct_chg": ("float", "涨跌幅", False),
            "vol": ("float", "成交量", False),
            "amount": ("float", "成交额", False),
        },
        "is_timescale": True,
        "chunk_interval": "7 days",
        "compress_after": "90 days",
        "quality_rules": [
            "no_null_price",
            "positive_volume",
            "reasonable_change",
            "price_consistency",
            "no_missing_dates",
        ],
    },
    "daily_basic": {
        "name": "每日指标",
        "api": "daily_basic",
        "mode": "incremental",
        "date_field": "trade_date",
        "schedule": "0 18 * * 1-5",
        "priority": 2,
        "oldest_date": "19910101",
        "api_date_type": "single",
        "verify_sample_size": 5,
        "fields": {
            "ts_code": ("str", "代码", True),
            "trade_date": ("date", "日期", True),
            "close": ("float", "收盘价", False),
            "turnover_rate": ("float", "换手率", False),
            "turnover_rate_f": ("float", "换手率(自由)", False),
            "volume_ratio": ("float", "量比", False),
            "pe": ("float", "PE", False),
            "pe_ttm": ("float", "PE-TTM", False),
            "pb": ("float", "PB", False),
            "ps": ("float", "PS", False),
            "ps_ttm": ("float", "PS-TTM", False),
            "dv_ratio": ("float", "股息率", False),
            "dv_ttm": ("float", "股息率TTM", False),
            "total_share": ("float", "总股本", False),
            "float_share": ("float", "流通股本", False),
            "free_share": ("float", "自由流通", False),
            "total_mv": ("float", "总市值", False),
            "circ_mv": ("float", "流通市值", False),
        },
        "is_timescale": True,
        "chunk_interval": "7 days",
        "compress_after": "90 days",
        "quality_rules": ["no_null_price", "reasonable_pe"],
    },
    "adj_factor": {
        "name": "复权因子",
        "api": "adj_factor",
        "mode": "incremental",
        "date_field": "trade_date",
        "schedule": "0 18 * * 1-5",
        "priority": 2,
        "oldest_date": "19910101",
        "api_date_type": "single",
        "verify_sample_size": 5,
        "fields": {
            "ts_code": ("str", "代码", True),
            "trade_date": ("date", "日期", True),
            "adj_factor": ("float", "复权因子", False),
        },
        "is_timescale": True,
        "chunk_interval": "7 days",
        "compress_after": "90 days",
        "quality_rules": ["adj_factor_positive"],
    },
    "fund_basic": {
        "name": "基金基本信息",
        "api": "fund_basic",
        "mode": "once",
        "schedule": "0 7 * * *",
        "priority": 3,
        "verify_sample_size": 0,
        "params": {},
        "fields": {
            "ts_code": ("str", "基金代码", True),
            "name": ("str", "简称", False),
            "management": ("str", "管理人", False),
            "custodian": ("str", "托管人", False),
            "fund_type": ("str", "投资类型", False),
            "found_date": ("date", "成立日期", False),
            "due_date": ("date", "到期日期", False),
            "list_date": ("date", "上市时间", False),
            "issue_date": ("date", "发行日期", False),
            "delist_date": ("date", "退市日期", False),
            "issue_amount": ("float", "发行份额(亿)", False),
            "m_fee": ("float", "管理费", False),
            "c_fee": ("float", "托管费", False),
            "duration_year": ("float", "存续期", False),
            "p_value": ("float", "面值", False),
            "min_amount": ("float", "起点金额(万)", False),
            "exp_return": ("float", "预期收益率", False),
            "benchmark": ("text", "业绩比较基准", False),
            "status": ("str", "存续状态", False),
            "invest_type": ("str", "投资风格", False),
            "type": ("str", "基金类型", False),
            "trustee": ("str", "受托人", False),
            "purc_startdate": ("date", "日常申购起始日", False),
            "redm_startdate": ("date", "日常赎回起始日", False),
            "market": ("str", "E场内O场外", False),
        },
        "is_timescale": False,
    },
    "fund_daily": {
        "name": "基金日线行情",
        "api": "fund_daily",
        "mode": "incremental",
        "date_field": "trade_date",
        "schedule": "0 19 * * 1-5",
        "priority": 4,
        "oldest_date": "20050101",
        "api_date_type": "single",
        "verify_sample_size": 5,
        "fields": {
            "ts_code": ("str", "基金代码", True),
            "trade_date": ("date", "交易日期", True),
            "open": ("float", "开盘价", False),
            "high": ("float", "最高价", False),
            "low": ("float", "最低价", False),
            "close": ("float", "收盘价", False),
            "pre_close": ("float", "昨收盘价", False),
            "change": ("float", "涨跌额", False),
            "pct_chg": ("float", "涨跌幅", False),
            "vol": ("float", "成交量", False),
            "amount": ("float", "成交额", False),
        },
        "is_timescale": True,
        "chunk_interval": "30 days",
        "quality_rules": ["no_null_price", "positive_volume"],
    },
    "moneyflow": {
        "name": "资金流向",
        "api": "moneyflow",
        "mode": "incremental",
        "date_field": "trade_date",
        "schedule": "0 20 * * 1-5",
        "priority": 5,
        "oldest_date": "20100101",
        "api_date_type": "single",
        "verify_sample_size": 5,
        "fields": {
            "ts_code": ("str", "代码", True),
            "trade_date": ("date", "日期", True),
            "buy_sm_vol": ("float", "小单买入量", False),
            "buy_sm_amount": ("float", "小单买入金额", False),
            "sell_sm_vol": ("float", "小单卖出量", False),
            "sell_sm_amount": ("float", "小单卖出金额", False),
            "buy_md_vol": ("float", "中单买入量", False),
            "buy_md_amount": ("float", "中单买入金额", False),
            "sell_md_vol": ("float", "中单卖出量", False),
            "sell_md_amount": ("float", "中单卖出金额", False),
            "buy_lg_vol": ("float", "大单买入量", False),
            "buy_lg_amount": ("float", "大单买入金额", False),
            "sell_lg_vol": ("float", "大单卖出量", False),
            "sell_lg_amount": ("float", "大单卖出金额", False),
            "buy_elg_vol": ("float", "特大单买入量", False),
            "buy_elg_amount": ("float", "特大单买入金额", False),
            "sell_elg_vol": ("float", "特大单卖出量", False),
            "sell_elg_amount": ("float", "特大单卖出金额", False),
            "net_mf_vol": ("float", "净流入量", False),
            "net_mf_amount": ("float", "净流入额", False),
        },
        "is_timescale": True,
        "chunk_interval": "7 days",
        "compress_after": "90 days",
    },
    "income": {
        "name": "利润表",
        "api": "income",
        "mode": "full",
        "date_field": "end_date",
        "schedule": "0 8 * * *",
        "priority": 6,
        "oldest_date": "19910101",
        "api_date_type": "code",
        "verify_sample_size": 0,
        "fields": {
            "ts_code": ("str", "代码", True),
            "ann_date": ("date", "公告日期", False),
            "f_ann_date": ("date", "实际公告日期", False),
            "end_date": ("date", "报告期", True),
            "report_type": ("str", "报告类型", False),
            "comp_type": ("str", "公司类型", False),
            "basic_eps": ("float", "基本每股收益", False),
            "diluted_eps": ("float", "稀释每股收益", False),
            "total_revenue": ("float", "营业总收入", False),
            "revenue": ("float", "营业收入", False),
            "n_income": ("float", "净利润", False),
            "n_income_attr_p": ("float", "归属母公司净利润", False),
            "compr_inc_attr_p": ("float", "归属母公司综合收益", False),
            "minority_gain": ("float", "少数股东损益", False),
            "total_profit": ("float", "利润总额", False),
            "income_tax": ("float", "所得税费用", False),
            "operate_profit": ("float", "营业利润", False),
            "n_commis_income": ("float", "手续费及佣金净收入", False),
            "oth_b_income": ("float", "其他业务收入", False),
            "fv_value_chg_gain": ("float", "公允价值变动净收益", False),
            "invest_income": ("float", "投资净收益", False),
            "total_cogs": ("float", "营业总成本", False),
            "oper_cost": ("float", "营业成本", False),
            "biz_tax_surchg": ("float", "营业税金及附加", False),
            "sell_exp": ("float", "销售费用", False),
            "admin_exp": ("float", "管理费用", False),
            "fin_exp": ("float", "财务费用", False),
            "assets_impair_loss": ("float", "资产减值损失", False),
            "update_flag": ("str", "更新标识", True),
        },
        "is_timescale": False,
    },
    "balancesheet": {
        "name": "资产负债表",
        "api": "balancesheet",
        "mode": "full",
        "date_field": "end_date",
        "schedule": "0 8 * * *",
        "priority": 6,
        "oldest_date": "19910101",
        "api_date_type": "code",
        "verify_sample_size": 0,
        "fields": {
            "ts_code": ("str", "代码", True),
            "ann_date": ("date", "公告日期", False),
            "f_ann_date": ("date", "实际公告日期", False),
            "end_date": ("date", "报告期", True),
            "report_type": ("str", "报表类型", False),
            "total_assets": ("float", "资产总计", False),
            "total_liab": ("float", "负债合计", False),
            "total_hldr_eqy_exc_min_int": ("float", "股东权益(不含少数)", False),
            "total_hldr_eqy_inc_min_int": ("float", "股东权益(含少数)", False),
            "money_cap": ("float", "货币资金", False),
            "accounts_receiv": ("float", "应收账款", False),
            "inventories": ("float", "存货", False),
            "fix_assets": ("float", "固定资产", False),
            "intan_assets": ("float", "无形资产", False),
            "goodwill": ("float", "商誉", False),
            "lt_borr": ("float", "长期借款", False),
            "st_borr": ("float", "短期借款", False),
            "total_cur_assets": ("float", "流动资产合计", False),
            "total_nca": ("float", "非流动资产合计", False),
            "total_cur_liab": ("float", "流动负债合计", False),
            "total_ncl": ("float", "非流动负债合计", False),
            "update_flag": ("str", "更新标识", True),
        },
        "is_timescale": False,
    },
    "cashflow": {
        "name": "现金流量表",
        "api": "cashflow",
        "mode": "full",
        "date_field": "end_date",
        "schedule": "0 8 * * *",
        "priority": 6,
        "oldest_date": "19910101",
        "api_date_type": "code",
        "verify_sample_size": 0,
        "fields": {
            "ts_code": ("str", "代码", True),
            "ann_date": ("date", "公告日期", False),
            "f_ann_date": ("date", "实际公告日期", False),
            "end_date": ("date", "报告期", True),
            "report_type": ("str", "报表类型", False),
            "n_cashflow_act": ("float", "经营活动现金流净额", False),
            "n_cashflow_inv_act": ("float", "投资活动现金流净额", False),
            "n_cash_flows_fnc_act": ("float", "筹资活动现金流净额", False),
            "free_cashflow": ("float", "自由现金流", False),
            "c_cash_equ_end_period": ("float", "期末现金余额", False),
            "n_incr_cash_cash_equ": ("float", "现金净增加额", False),
            "c_fr_sale_sg": ("float", "销售商品收到现金", False),
            "c_paid_goods_s": ("float", "购买商品支付现金", False),
            "c_paid_to_for_empl": ("float", "支付给职工现金", False),
            "c_paid_for_taxes": ("float", "支付的各项税费", False),
            "c_recp_borrow": ("float", "取得借款收到现金", False),
            "c_prepay_amt_borr": ("float", "偿还债务支付现金", False),
            "c_pay_dist_dpcp_int_exp": ("float", "分配股利偿付利息", False),
            "update_flag": ("str", "更新标识", True),
        },
        "is_timescale": False,
    },
    "fina_indicator": {
        "name": "财务指标",
        "api": "fina_indicator",
        "mode": "full",
        "date_field": "end_date",
        "schedule": "0 8 * * *",
        "priority": 6,
        "oldest_date": "19910101",
        "api_date_type": "code",
        "verify_sample_size": 0,
        "fields": {
            "ts_code": ("str", "代码", True),
            "ann_date": ("date", "公告日期", False),
            "end_date": ("date", "报告期", True),
            "eps": ("float", "基本每股收益", False),
            "dt_eps": ("float", "稀释每股收益", False),
            "bps": ("float", "每股净资产", False),
            "roe": ("float", "净资产收益率", False),
            "roe_waa": ("float", "加权ROE", False),
            "roe_dt": ("float", "扣非ROE", False),
            "roa": ("float", "总资产报酬率", False),
            "grossprofit_margin": ("float", "销售毛利率", False),
            "netprofit_margin": ("float", "销售净利率", False),
            "current_ratio": ("float", "流动比率", False),
            "quick_ratio": ("float", "速动比率", False),
            "debt_to_assets": ("float", "资产负债率", False),
            "assets_turn": ("float", "总资产周转率", False),
            "op_yoy": ("float", "营业利润同比", False),
            "netprofit_yoy": ("float", "净利润同比", False),
            "tr_yoy": ("float", "营业总收入同比", False),
            "or_yoy": ("float", "营业收入同比", False),
            "dt_netprofit_yoy": ("float", "扣非净利润同比", False),
            "ocf_yoy": ("float", "经营现金流同比", False),
            "roe_yoy": ("float", "ROE同比", False),
            "rd_exp": ("float", "研发费用", False),
            "update_flag": ("str", "更新标识", True),
        },
        "is_timescale": False,
    },
    "fina_audit": {
        "name": "财务审计意见",
        "api": "fina_audit",
        "mode": "full",
        "date_field": "end_date",
        "schedule": "0 8 * * *",
        "priority": 6,
        "oldest_date": "19910101",
        "api_date_type": "code",
        "verify_sample_size": 0,
        "fields": {
            "ts_code": ("str", "代码", True),
            "ann_date": ("date", "公告日期", False),
            "end_date": ("date", "报告期", True),
            "audit_result": ("str", "审计结果", False),
            "audit_fees": ("float", "审计费用", False),
            "audit_agency": ("str", "审计机构", False),
            "audit_sign": ("str", "签字会计师", False),
        },
        "is_timescale": False,
    },
    # ====== Index (指数) ======
    "index_basic": {
        "name": "指数基本信息",
        "api": "index_basic",
        "mode": "once",
        "schedule": "0 5 * * *",
        "priority": 1,
        "api_date_type": "none",
        "verify_sample_size": 0,
        "params": {"market": ""},
        "fields": {
            "ts_code": ("str", "指数代码", True),
            "name": ("str", "指数名称", False),
            "market": ("str", "市场", False),
            "publisher": ("str", "发布方", False),
            "category": ("str", "指数类别", False),
            "base_date": ("str", "基准日期", False),
            "base_point": ("float", "基准点位", False),
            "list_date": ("str", "发布日期", False),
        },
        "is_timescale": False,
    },
    "index_daily": {
        "name": "指数日线",
        "api": "index_daily",
        "mode": "incremental",
        "date_field": "trade_date",
        "schedule": "0 19 * * 1-5",
        "priority": 3,
        "oldest_date": "19910101",
        "api_date_type": "code",
        "code_source": "index_basic",
        "code_field": "ts_code",
        "code_filter": "category IN ('综合指数','规模指数')",
        "verify_sample_size": 0,
        "fields": {
            "ts_code": ("str", "指数代码", True),
            "trade_date": ("date", "交易日期", True),
            "close": ("float", "收盘点位", False),
            "open": ("float", "开盘点位", False),
            "high": ("float", "最高点位", False),
            "low": ("float", "最低点位", False),
            "pre_close": ("float", "昨收点位", False),
            "change": ("float", "涨跌点", False),
            "pct_chg": ("float", "涨跌幅", False),
            "vol": ("float", "成交量", False),
            "amount": ("float", "成交额", False),
        },
        "is_timescale": True,
        "chunk_interval": "7 days",
    },
    "index_weekly": {
        "name": "指数周线",
        "api": "index_weekly",
        "mode": "incremental",
        "date_field": "trade_date",
        "schedule": "0 20 * * 5",
        "priority": 4,
        "oldest_date": "19910101",
        "api_date_type": "code",
        "code_source": "index_basic",
        "code_field": "ts_code",
        "code_filter": "category IN ('综合指数','规模指数')",
        "verify_sample_size": 0,
        "fields": {
            "ts_code": ("str", "指数代码", True),
            "trade_date": ("date", "交易日期", True),
            "close": ("float", "收盘点位", False),
            "open": ("float", "开盘点位", False),
            "high": ("float", "最高点位", False),
            "low": ("float", "最低点位", False),
            "pre_close": ("float", "昨收点位", False),
            "change": ("float", "涨跌点", False),
            "pct_chg": ("float", "涨跌幅", False),
            "vol": ("float", "成交量", False),
            "amount": ("float", "成交额", False),
        },
        "is_timescale": True,
        "chunk_interval": "30 days",
    },
    "index_monthly": {
        "name": "指数月线",
        "api": "index_monthly",
        "mode": "incremental",
        "date_field": "trade_date",
        "schedule": "0 20 1 * *",
        "priority": 4,
        "oldest_date": "19910101",
        "api_date_type": "code",
        "code_source": "index_basic",
        "code_field": "ts_code",
        "code_filter": "category IN ('综合指数','规模指数')",
        "verify_sample_size": 0,
        "fields": {
            "ts_code": ("str", "指数代码", True),
            "trade_date": ("date", "交易日期", True),
            "close": ("float", "收盘点位", False),
            "open": ("float", "开盘点位", False),
            "high": ("float", "最高点位", False),
            "low": ("float", "最低点位", False),
            "pre_close": ("float", "昨收点位", False),
            "change": ("float", "涨跌点", False),
            "pct_chg": ("float", "涨跌幅", False),
            "vol": ("float", "成交量", False),
            "amount": ("float", "成交额", False),
        },
        "is_timescale": True,
        "chunk_interval": "90 days",
    },
    "index_weight": {
        "name": "指数成分和权重",
        "api": "index_weight",
        "mode": "incremental",
        "date_field": "trade_date",
        "schedule": "0 21 * * 5",
        "priority": 5,
        "oldest_date": "20050101",
        "api_date_type": "code",
        "code_source": "index_basic",
        "code_field": "index_code",
        "code_filter": "category IN ('综合指数','规模指数')",
        "verify_sample_size": 0,
        "fields": {
            "index_code": ("str", "指数代码", True),
            "con_code": ("str", "成分代码", True),
            "trade_date": ("date", "交易日期", True),
            "weight": ("float", "权重", False),
        },
        "is_timescale": True,
        "chunk_interval": "30 days",
    },
    "index_dailybasic": {
        "name": "大盘指数每日指标",
        "api": "index_dailybasic",
        "mode": "incremental",
        "date_field": "trade_date",
        "schedule": "0 19 * * 1-5",
        "priority": 3,
        "oldest_date": "20050101",
        "api_date_type": "single",
        "verify_sample_size": 0,
        "fields": {
            "ts_code": ("str", "指数代码", True),
            "trade_date": ("date", "交易日期", True),
            "total_mv": ("float", "总市值", False),
            "float_mv": ("float", "流通市值", False),
            "total_share": ("float", "总股本", False),
            "float_share": ("float", "流通股本", False),
            "free_share": ("float", "自由流通股本", False),
            "turnover_rate": ("float", "换手率", False),
            "turnover_rate_f": ("float", "换手率(自由流通)", False),
            "pe": ("float", "市盈率", False),
            "pe_ttm": ("float", "市盈率TTM", False),
            "pb": ("float", "市净率", False),
        },
        "is_timescale": True,
        "chunk_interval": "7 days",
    },
}
