apiVersion: 1

datasources:
  - name: QuantPostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: quant_db
    user: quant
    secureJsonData:
      password: quant123
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
